// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import '../../data/models/journal_entry.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 4628118165187590185),
    name: 'JournalEntity',
    lastPropertyId: const obx_int.IdUid(8, 85002401557886598),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 9157359421142798432),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 865220379588436509),
        name: 'content',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1512654159687451460),
        name: 'summary',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 3091145750923595319),
        name: 'tags',
        type: 30,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5654551869104107351),
        name: 'mood',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 4792641283013721215),
        name: 'isPosted',
        type: 1,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 4291263561079624141),
        name: 'createdAt',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 85002401557886598),
        name: 'title',
        type: 9,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 4628118165187590185),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    JournalEntity: obx_int.EntityDefinition<JournalEntity>(
      model: _entities[0],
      toOneRelations: (JournalEntity object) => [],
      toManyRelations: (JournalEntity object) => {},
      getId: (JournalEntity object) => object.id,
      setId: (JournalEntity object, int id) {
        object.id = id;
      },
      objectToFB: (JournalEntity object, fb.Builder fbb) {
        final contentOffset = fbb.writeString(object.content);
        final summaryOffset = object.summary == null
            ? null
            : fbb.writeString(object.summary!);
        final tagsOffset = object.tags == null
            ? null
            : fbb.writeList(
                object.tags!.map(fbb.writeString).toList(growable: false),
              );
        final moodOffset = object.mood == null
            ? null
            : fbb.writeString(object.mood!);
        final titleOffset = fbb.writeString(object.title);
        fbb.startTable(9);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, contentOffset);
        fbb.addOffset(2, summaryOffset);
        fbb.addOffset(3, tagsOffset);
        fbb.addOffset(4, moodOffset);
        fbb.addBool(5, object.isPosted);
        fbb.addInt64(6, object.createdAt.millisecondsSinceEpoch);
        fbb.addOffset(7, titleOffset);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final titleParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 18, '');
        final contentParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final summaryParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 8);
        final tagsParam = const fb.ListReader<String>(
          fb.StringReader(asciiOptimization: true),
          lazy: false,
        ).vTableGetNullable(buffer, rootOffset, 10);
        final moodParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGetNullable(buffer, rootOffset, 12);
        final isPostedParam = const fb.BoolReader().vTableGet(
          buffer,
          rootOffset,
          14,
          false,
        );
        final createdAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = JournalEntity(
          id: idParam,
          title: titleParam,
          content: contentParam,
          summary: summaryParam,
          tags: tagsParam,
          mood: moodParam,
          isPosted: isPostedParam,
          createdAt: createdAtParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [JournalEntity] entity fields to define ObjectBox queries.
class JournalEntity_ {
  /// See [JournalEntity.id].
  static final id = obx.QueryIntegerProperty<JournalEntity>(
    _entities[0].properties[0],
  );

  /// See [JournalEntity.content].
  static final content = obx.QueryStringProperty<JournalEntity>(
    _entities[0].properties[1],
  );

  /// See [JournalEntity.summary].
  static final summary = obx.QueryStringProperty<JournalEntity>(
    _entities[0].properties[2],
  );

  /// See [JournalEntity.tags].
  static final tags = obx.QueryStringVectorProperty<JournalEntity>(
    _entities[0].properties[3],
  );

  /// See [JournalEntity.mood].
  static final mood = obx.QueryStringProperty<JournalEntity>(
    _entities[0].properties[4],
  );

  /// See [JournalEntity.isPosted].
  static final isPosted = obx.QueryBooleanProperty<JournalEntity>(
    _entities[0].properties[5],
  );

  /// See [JournalEntity.createdAt].
  static final createdAt = obx.QueryDateProperty<JournalEntity>(
    _entities[0].properties[6],
  );

  /// See [JournalEntity.title].
  static final title = obx.QueryStringProperty<JournalEntity>(
    _entities[0].properties[7],
  );
}
